### ISSUE TITLE
improvement proposal

### ISSUE THREAD

**Issue by ggghamd** [amddcgpuce/rocmtechsupport#17]
I have been working on following script: https://gitlab1.amd.com/cst/gscript/-/blob/master/scripts/techsupport_v2.sh
Before pull requets, since it is drastically different, can some or all of the features integrated/posrted (feature list below)?
I see this one generates one long log:
Changes that can be integrated/ported:
* --help menu
* summary log + detailed sublogs (below for log file hierarchies) + consistent naming scheme. 
* detail sublog: generated separate log for each component (pcie, kfd, dmesg, sysfiles, rocmsmi, rocminfo, ip etc)
* automatically generate tar.gz with all logs. 
* support for centos/ubuntu, sles(pending)
*  gather log from VM (kvm) and store on host (optionally)
* capture date/time string in the log name.

log file structure:
```
ts/
      <DATE>
          <DATE>-platform-summary log (containing overall information on host + guest(if applicable)
<DATE->-techsupport.tar
          host part: cpu, gpu model, amdgpu/libgv version, kernel versO/Sn, host os version.
          guest part: cpu, gpu mod(guest) version, kernel version, guest O/S version.
      host/
          host logs: dmesg, modi(or libgv) info amdgpu, amdgpu(or libgv) parameters, rocminfo, rocm-smi.
      guest/
          guest logs: dmesg, modinfo amdgpu, amdgpu parameters, rocminfo, rocm-smi.
```

**Comment by amddcgpuce** [comment]
@ggghamd  The purpose of this script is have one log file that has all the information in different sections, all in one place. Having different files adds complexity to correlation messages with data, which becomes more difficult as time passes.
